sudo: required
services:
  - docker

before_install:
  - docker build -t kdt1802/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kdt1802/react-test npm test

after_success:
  - docker build -t kdt1802/multi-client ./client
  - docker build -t kdt1802/multi-nginx ./nginx
  - docker build -t kdt1802/multi-server ./server
  - docker build -t kdt1802/multi-worker ./worker
  # login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push kdt1802/multi-client
  - docker push kdt1802/multi-nginx
  - docker push kdt1802/multi-server
  - docker push kdt1802/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-412805220065'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
